=== RuiFerreira05/After-The-End/src/main/java/tps/tp4/xml/colony.dtd
<!ELEMENT colony (colonyName, currDay, resources, production, population, settlers, structures)>
<!ELEMENT colonyName (#PCDATA)>
<!ELEMENT currDay (#PCDATA)>
<!ELEMENT resources (wood, food, stone, metal, entertainment)>
<!ELEMENT wood (#PCDATA)>
<!ELEMENT food (#PCDATA)>
<!ELEMENT stone (#PCDATA)>
<!ELEMENT metal (#PCDATA)>
<!ELEMENT entertainment (#PCDATA)>
<!ELEMENT production (woodProduction, foodProduction, stoneProduction, metalProduction)>
<!ELEMENT woodProduction (#PCDATA)>
<!ELEMENT foodProduction (#PCDATA)>
<!ELEMENT stoneProduction (#PCDATA)>
<!ELEMENT metalProduction (#PCDATA)>
<!ELEMENT population (current, max, warriors, maxWarriors)>
<!ELEMENT current (#PCDATA)>
<!ELEMENT max (#PCDATA)>
<!ELEMENT warriors (#PCDATA)>
<!ELEMENT maxWarriors (#PCDATA)>
<!ELEMENT settlers (settler*)>
<!ELEMENT settler (name, age, health, happiness, entertainmentImpact, foodImpact, healthImpact)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT health (#PCDATA)>
<!ELEMENT happiness (#PCDATA)>
<!ELEMENT entertainmentImpact (#PCDATA)>
<!ELEMENT foodImpact (#PCDATA)>
<!ELEMENT healthImpact (#PCDATA)>
<!ELEMENT structures (structure*)>
<!ELEMENT structure (type, count)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT count (#PCDATA)>

=== RuiFerreira05/After-The-End/src/main/resources/xml/colony.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colony SYSTEM "colony.dtd">
<colony>
    <colonyName>NewHope</colonyName>
    <currDay>5</currDay>
    <resources>
        <wood>350</wood>
        <food>420</food>
        <stone>180</stone>
        <metal>90</metal>
        <entertainment>10</entertainment>
    </resources>
    <production>
        <woodProduction>2</woodProduction>
        <foodProduction>3</foodProduction>
        <stoneProduction>1</stoneProduction>
        <metalProduction>1</metalProduction>
    </production>
    <population>
        <current>4</current>
        <max>13</max>
        <warriors>1</warriors>
        <maxWarriors>6</maxWarriors>
    </population>
    <settlers>
        <settler>
            <name>John</name>
            <age>32</age>
            <health>100</health>
            <happiness>95</happiness>
            <entertainmentImpact>0.25</entertainmentImpact>
            <foodImpact>0.50</foodImpact>
            <healthImpact>0.25</healthImpact>
        </settler>
        <settler>
            <name>Jane</name>
            <age>27</age>
            <health>98</health>
            <happiness>90</happiness>
            <entertainmentImpact>0.30</entertainmentImpact>
            <foodImpact>0.40</foodImpact>
            <healthImpact>0.30</healthImpact>
        </settler>
    </settlers>
    <structures>
        <structure>
            <type>house</type>
            <count>2</count>
        </structure>
    </structures>
</colony>
