=== RuiFerreira05/After-The-End/src/main/java/tps/tp4/settings/settings.dtd
<!ELEMENT settings (
    initial,
    building+
)>

<!ELEMENT initial (
    maxPopulation,
    wood,
    food,
    stone,
    metal,
    entertainment,
    woodProduction,
    foodProduction,
    stoneProduction,
    metalProduction
)>

<!ELEMENT maxPopulation (#PCDATA)>
<!ELEMENT wood (#PCDATA)>
<!ELEMENT food (#PCDATA)>
<!ELEMENT stone (#PCDATA)>
<!ELEMENT metal (#PCDATA)>
<!ELEMENT entertainment (#PCDATA)>
<!ELEMENT woodProduction (#PCDATA)>
<!ELEMENT foodProduction (#PCDATA)>
<!ELEMENT stoneProduction (#PCDATA)>
<!ELEMENT metalProduction (#PCDATA)>

<!ELEMENT building (
    cost,
    production,
    populationIncrease?,
    warriorsIncrease?
)>
<!ATTLIST building name CDATA #REQUIRED>

<!ELEMENT cost EMPTY>
<!ATTLIST cost
    wood CDATA #REQUIRED
    stone CDATA #REQUIRED
    metal CDATA #REQUIRED
>

<!ELEMENT production EMPTY>
<!ATTLIST production
    wood CDATA #REQUIRED
    food CDATA #REQUIRED
    stone CDATA #REQUIRED
    metal CDATA #REQUIRED
    entertainment CDATA #REQUIRED
>

<!ELEMENT populationIncrease (#PCDATA)>
<!ELEMENT warriorsIncrease (#PCDATA)>

=== RuiFerreira05/After-The-End/src/main/java/tps/tp4/settings/user_settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="settings.dtd" type="application/xml-dtd"?>
<!DOCTYPE settings SYSTEM "settings.dtd">

<settings>
    <initial>
        <maxPopulation>10</maxPopulation>
        <wood>500</wood>
        <food>500</food>
        <stone>500</stone>
        <metal>500</metal>
        <entertainment>0</entertainment>
        <woodProduction>0</woodProduction>
        <foodProduction>0</foodProduction>
        <stoneProduction>0</stoneProduction>
        <metalProduction>0</metalProduction>
    </initial>
    <building name="house">
        <cost wood="100" stone="10" metal="0"/>
        <production wood="0" food="0" stone="0" metal="0" entertainment="0"/>
        <populationIncrease>3</populationIncrease>
    </building>
    <building name="farm">
        <cost wood="50" stone="0" metal="0"/>
        <production wood="0" food="1" stone="0" metal="0" entertainment="0"/>
    </building>
    <building name="factory">
        <cost wood="200" stone="50" metal="0"/>
        <production wood="0" food="0" stone="0" metal="1" entertainment="0"/>
    </building>
    <building name="hospital">
        <cost wood="100" stone="50" metal="0"/>
        <production wood="0" food="0" stone="0" metal="0" entertainment="0"/>
    </building>
    <building name="woodcutterLodge">
        <cost wood="50" stone="0" metal="0"/>
        <production wood="1" food="0" stone="0" metal="0" entertainment="0"/>
    </building>
    <building name="mine">
        <cost wood="100" stone="0" metal="0"/>
        <production wood="0" food="0" stone="1" metal="0" entertainment="0"/>
    </building>
    <building name="barracks">
        <cost wood="200" stone="100" metal="0"/>
        <production wood="0" food="0" stone="0" metal="0" entertainment="0"/>
        <warriorsIncrease>5</warriorsIncrease>
    </building>
</settings>
